In [4]:
import numpy as np
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1], [17.3, 22.8, 30.5, 26.4, 21.9], [33.1,29.6, 18.4, 24.0, 27.8], [20.2, 23.5, 31.9, 28.1, 22.6]])
#Task 1: Print Shape and Mean per station
print("Shape of Data:" , data.shape)
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:" , mean_per_station)
mask = data > 28.0
temps_above_28 = data[mask]
print("Temperatures readings above 28.0°C (1D Array):" , temps_above_28)
normalized = (data - data.min()) / (data.max() - data.min())
print("Normalized data (rounded to 2 decimal places):")
print(np.round(normalized, 2))




Shape of Data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]
Temperatures readings above 28.0°C (1D Array): [31.2 28.7 30.5 33.1 29.6 31.9 28.1]
Normalized data (rounded to 2 decimal places):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
